"
" General
"

" Use Vim settings, rather than Vi settings
set nocompatible

" Disable Q command (Ex mode)
nnoremap Q <Nop>

" Disable bell sounds
set belloff=all

" Enable mouse
if has('mouse')
    set mouse=a
endif

" Set utf-8 encoding
set encoding=utf-8

"
" Editing
"

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Map CTRL-backspace to delete word before the cursor
inoremap <C-BS> <C-W>
" Also map CTRL-H because CTRL-backspace doesn't work in terminals
inoremap <C-H> <C-W>

" Map CTRL-down/up to move by a paragraph in insert mode
inoremap <C-Down> <C-O>}
inoremap <C-Up> <C-O>{

" Time out on key codes, making Esc take effect more quickly
set ttimeout
set ttimeoutlen=50

"
" Appearance
"

set termguicolors
set background=light
colorscheme base16-tomorrow

" Show the cursor position all the time
set ruler

" Display incomplete commands
set showcmd

" Display command-line completion matches in a status line
set wildmenu

" Show @@@ in the last column of the last line if it is truncated
set display=lastline

" Switch syntax highlighting on
syntax on

" Line numbers
set number
set relativenumber

" Folds
set foldcolumn=1

" Highlight line of the cursor
set cursorline

" Add context around cursor
set scrolloff=6

" Display tabs and trailing spaces
set list
set listchars=tab:>-,trail:-

"
" Indentation
"

set tabstop=4
set shiftwidth=4
set expandtab
set shiftround
set autoindent

"
" Files
"

" Backup current file, deleted afterwards
set nobackup
set writebackup

"
" Filetypes
"

" Detect filetype and load indent files
filetype plugin indent on

" Set indent style for C
set cinoptions=:0,l1,g0,E-s,(0,W1s

"
" Searching
"

" Do incremental searching when it's possible to timeout
if has('reltime')
  set incsearch
endif

" Highlight search results
set hlsearch

"
" Windows specific
"

if has('win32')
    " Windows include dirs
    if isdirectory('C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um')
        set path+=C:/Program\\\ Files\\\ (x86)/Windows\\\ Kits/10/Include/10.0.19041.0/um
    endif

    " Windows build batch files
    if filereadable('./build.bat')
        set makeprg=\".\build.bat\"
    elseif filereadable('./src/build.bat')
        set makeprg=\".\src\build.bat\"
    endif
endif

