" allow backspace
set backspace=indent,eol,start

" appearance
set termguicolors
"let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
"let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
syntax enable
set background=light
colorscheme base16-tomorrow

" display tabs and trailing spaces
set list
set listchars=tab:>-,trail:-

" line numbers
set number
set relativenumber

" folds
set foldcolumn=1

" highlight line of the cursor
set cursorline

" highlight search results
set hlsearch

" add context around cursor
set scrolloff=6

" backup current file, deleted afterwards
set nobackup
set writebackup

" indentation
set tabstop=4
set shiftwidth=4
set expandtab
set shiftround
set autoindent
set cinoptions=l1,(0,W1s

" filetype detection
filetype plugin indent on

" reduce key code sequence timeout to speed up O new line after exiting insert mode
set ttimeoutlen=50

" disable bell sounds
set belloff=all

" mouse
if !has('nvim')
    set ttymouse=sgr
endif
set mouse=a

" set utf-8 encoding
set encoding=utf-8

" Windows specific options
if has('win32')
    " Windows include dirs
    if isdirectory('C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um')
        set path+=C:/Program\\\ Files\\\ (x86)/Windows\\\ Kits/10/Include/10.0.19041.0/um
    endif

    " Windows build batch files
    if filereadable('./build.bat')
        set makeprg=\".\build.bat\"
    elseif filereadable('./src/build.bat')
        set makeprg=\".\src\build.bat\"
    endif
endif
