vo=gpu
profile=gpu-hq
gpu-context=wayland

hwdec=vaapi
hwdec-codecs=all

scale=ewa_lanczossharp
cscale=ewa_lanczossharp

video-sync=display-resample
interpolation
tscale=oversample

keep-open
sub-auto=all

script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format="bestvideo*[height<=?1440]+bestaudio/best[height<=?1440]"

screenshot-directory=~/Pictures
